Init project
DeGusar/crypto-vue pull request #1
Opened 2023-07-29 13:08 UTC by DeGusar

Initialization of the project

2023-07-31 10:54 UTC, dzhuravkov requested changes

2023-07-31 10:54 UTC, dzhuravkov commented on README.md
> +# Vue 3 + Vite
Nice Read me =) I think we can remove this and add Vue 2 project.

2023-07-31 10:54 UTC, dzhuravkov commented on src/App.vue
> +
empty string.

2023-07-31 10:54 UTC, dzhuravkov commented on src/assets/styles/common/spinner.scss
> +    // border-top: 2px solid $color-purple-dark;
remove comment

2023-07-31 10:54 UTC, dzhuravkov commented on src/assets/styles/helpers/index.scss
> +@import "./variables"
empty line for every file at the end.

2023-07-31 10:54 UTC, dzhuravkov commented on src/components/basicComponents/index.js
> +import RouterLinkComponent from "./RouterLinkComponent.vue";
Do we need to write a .vue extension to import? I think plating for Vite should help to avoid this.

2023-07-31 10:54 UTC, dzhuravkov commented on src/router/index.js
> +      layout: layoutNames.MAIN_LAYOUT,
I want to suggest another approach for you because we've already used this one.

You need to create 2 files in the layout: ErrorLayout, MainLayout.
'/' will use MainLayout
but '/error' will use ErrorLayout.

```
  {
    path: "/",
    component: MainLayout
    redirect { to the main page },
    children: [ all pages for main layout ] 
  },
  {
     path: "/error",
    component: ErrorLayout,
    children: [ all error pages ]
```

after that, we can remove all logic related to meta form router and components.
We use this approach on the project.

2023-07-31 10:54 UTC, dzhuravkov commented on src/utils/constants/layoutNames.js
> +  MAIN_LAYOUT: "MainLayout",
Use one approach for naming. You've already used  IS_LOADING: "IS_LOADING" name approach.

2023-07-31 10:54 UTC, dzhuravkov commented on src/views/Error404Page/index.vue
> +
No need for spaces in option API between sections, check all places.

2023-07-31 10:54 UTC, dzhuravkov commented on src/views/Error404Page/index.vue
> +  .error404-page {
no need empty space here before class name.

2023-07-31 10:54 UTC, dzhuravkov commented on src/views/MainPage/MainPageHistory/index.vue
> +  <div>History</div>
Use <section tag as a container of the page check all places.

2023-07-31 10:54 UTC, dzhuravkov commented on src/layouts/MainLayout.vue
> +        <slot />
Check my comment in the router.js.
We can change the slot to the router-view after the changes.

2023-07-31 10:54 UTC, dzhuravkov commented on src/layouts/MainLayout.vue
> +      <div class="main-layout__content">
Hmm, 3 nested divs look not nice for only one content in the end. Looks like we can use only one. This nested staff shows us that something is not nice with styles, and we need to take a look at them.

2023-07-31 10:54 UTC, dzhuravkov commented on package.json
> +    "vite-plugin-vue2": "^2.0.3",
Recheck dependencies I think a couple of them are related only to devDependencies.
I think we can add a eslint, because I see a few problems with formatting. (eslint only, I think we don't need a CSS lint at that moment)

2023-07-31 10:54 UTC, dzhuravkov commented on src/components/basicComponents/RouterLinkComponent.vue
> +      type: [Object, String],
For basic components nice practice to use validators for props.
We can check if it string does nothing, but if this is an object we always should have a name field.
validators help developers to understand your component better and avoid an error in the future if we pass a null for example.
Validation is only a nice feature for common (basic) components, don't use validators for every vue file.

2023-08-01 13:18 UTC, dzhuravkov requested changes

2023-08-01 13:18 UTC, dzhuravkov commented on src/components/basicComponents/RouterLinkComponent.vue
> +    (propData instanceof Object &&
you can write this method more declarative.
use if at first and check if is it an Object and then return your prototype check.
and at the end of function return just checking for String.

2023-08-01 13:18 UTC, dzhuravkov commented on src/App.vue
> +
I still see a empty string

2023-08-02 08:33 UTC, dzhuravkov requested changes

2023-08-02 08:33 UTC, dzhuravkov commented on vite.config.js
> +    },
We decided to use extensions here, and remove construction with '../index' and '.vue'

2023-08-02 11:37 UTC, DeGusar commented on vite.config.js
> +    },
I added it in the next pull-request

2023-08-02 12:01 UTC, dzhuravkov approved these changes

2023-08-02 12:01 UTC, merged